# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
